openapi: 3.0.1
servers:
  - description: SwaggerHub API
    url: HTTP
  - description: SwaggerHub API
    url: HTTPS
info:
  description: Library API
  version: "1.0.0"
  title: Simple library API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: users
    description: Operations available to regular users
  # - name: employers
  #   description: Mananger of the employees
paths:
  /books:
    $ref: "./components/books/books.yaml"
  /books/{bookId}:
    $ref: "./components/books/book/book.yaml"
  /users:
    $ref: "./components/users/users.yaml"
  /users/{userId}:
    get:
      tags:
        - admins
      summary: Get a user by ID
      parameters:
      responses:
      "200":
        description: a single user.
        content:
          application/json:
            schema:
              $ref: "./components/schemas/userItem.yaml"

  /authors:
    $ref: "./components/authors/authors.yaml"
  /authors/{authorId}:
    get:
      tags:
        - users
        - admins
      summary: Get an author by ID
      parameters:
      responses:
      "200":
        description: a single author.
        content:
          application/json:
            schema:
              $ref: "./components/schemas/authorItem.yaml"
components:
  schemas:
    book Item:
      $ref: "./components/schemas/bookItem.yaml"
    User Item:
      $ref: "./components/schemas/userItem.yaml"
    author Item:
      $ref: "./components/schemas/authorItem.yaml"

    Manufacturer:
      $ref: "./components/schemas/Manufacturer.yaml"
    securitySchemes:
      $ref: "./components/schemas/securitySchemes.yaml"
